### PR TITLE
Changed how vanilla villagers are detected

### PR DESCRIPTION
**Pull request by recalcitrantQ**
This should fix issue #910 . I have not yet tested for side effects but it does get multiplayer playable

### CODE REVIEW

**Comment by minecrafter2334** [comment]
I am on mac. can you tell me how to implement the fix

**Comment by recalcitrantQ** [comment]
You'll have to download the branch and build the jar. There are guides saying how to do this is you are unfamiliar with gradle

**Comment by minecrafter2334** [comment]
where can I download the branch

**Comment by minecrafter2334** [comment]
Or do you have a file with the fix

**Comment by minecrafter2334** [comment]
I'm not familiar with building jars or gradle

**Comment by CrazyCowboy557** [comment]
I really hope this gets merged. I love MCA, but this bug prevents me from using it on a server.

**Pull request closed without merging**
